// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import process from "process";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations and introspection: use direct Postgres when set (bypasses PgBouncer/transaction mode).
    // Otherwise same as DATABASE_URL.
    url:
      process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
